# Generated by Django 4.0.5 on 2022-09-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelo',
            old_name='dia',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='vuelo',
            old_name='hora_s',
            new_name='hora_de_salida',
        ),
    ]
